

GET http://localhost:5111/WeatherForecast/GetWeatherForecast/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiam9obiIsImp0aSI6IjI1ZjYyNTEwLTZiMzAtNGVhNi05NjA2LTU3ODYzZWQ3ZWFiZCIsImV4cCI6MTY4NjEyNTk3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTExIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo0MjAwIn0.UFDyIhxCV3JahsndXZWeyiBmIgGS8SLF1A3yGZOpNww